name: Generate and Deploy Sitemap & Robots

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Generate sitemap.xml
      - name: Generate sitemap.xml
        run: |
          echo '<?xml version="1.0" encoding="UTF-8"?>' > sitemap.xml
          echo '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' >> sitemap.xml
          echo '<url><loc>https://meowwarex.com/</loc><changefreq>daily</changefreq><priority>1.0</priority></url>' >> sitemap.xml
          echo '</urlset>' >> sitemap.xml

      # Step 3: Generate robots.txt
      - name: Generate robots.txt
        run: |
          echo 'User-agent: *' > robots.txt
          echo 'Disallow: /admin/' >> robots.txt
          echo 'Disallow: /login/' >> robots.txt
          echo 'Allow: /public/' >> robots.txt
          echo 'Sitemap: https://meowwarex.com/sitemap.xml' >> robots.txt

      # Step 4: Deploy sitemap.xml and robots.txt to Hostinger
      - name: Deploy sitemap.xml and robots.txt to Hostinger
        uses: SamKirkland/FTP-Deploy-Action@v4.3.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: ./
          exclude: |
            .git/**                # Excluye la carpeta .git completa
            node_modules/**        # Excluye node_modules (si aplica)
            **/*.scss              # Excluye archivos .scss
            !sitemap.xml           # Incluye explícitamente sitemap.xml
            !robots.txt            # Incluye explícitamente robots.txt
          dry-run: false           # Cambia a true para probar sin subir archivos
