name: Compress Images

on:
  push:
    branches:
      - main
    paths:
      - '**/*.jpg'
      - '**/*.jpeg'
      - '**/*.png'
      - '**/*.webp'

jobs:
  compress-images:
    name: Compress Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Compress Images
        uses: photogabble/image-actions@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          paths: |
            images/** 
            img/**    
          extensions: jpg,jpeg,png,webp
          quality: 80
          strip_metadata: true
